In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train = pd.read_parquet("../data/processed/train.parquet")
test =  pd.read_parquet("../data/processed/test.parquet")
val =  pd.read_parquet("../data/processed/val.parquet")

In [3]:
train

         user_id  item_id last_watch_dt  total_dur  watched_pct
0         176549     9506    2021-05-11       4250         72.0
1         699317     1659    2021-05-29       8317        100.0
2         656683     7107    2021-05-09         10          0.0
3         864613     7638    2021-07-05      14483        100.0
4         964868     9506    2021-04-30       6725        100.0
...          ...      ...           ...        ...          ...
3787041   268216     3071    2021-04-21       5752         98.0
3787042   497899     9629    2021-05-29         45          1.0
3787043   786732     4880    2021-05-12        753          0.0
3787044   546862     9673    2021-04-13       2308         49.0
3787045   384202    16197    2021-04-19       6203        100.0

[3787046 rows x 5 columns]

In [4]:
test

        user_id  item_id last_watch_dt  total_dur  watched_pct
0        377423    15373    2021-08-06        202          3.0
1        127724     5658    2021-08-07       2447         45.0
2        200197     9335    2021-08-16         83          2.0
3        580093    15411    2021-08-11      10479        100.0
4        739920     3190    2021-08-05       3349         48.0
...         ...      ...           ...        ...          ...
474125   590892     8618    2021-08-21       1335         23.0
474126   273558    10605    2021-08-21      34030        100.0
474127   974756    12173    2021-08-08      11608        100.0
474128    24262     7865    2021-08-08      12967        100.0
474129  1073802     9927    2021-08-07       6425         97.0

[474130 rows x 5 columns]

In [5]:
val

        user_id  item_id last_watch_dt  total_dur  watched_pct
0        215229     7793    2021-08-01        873         14.0
1         81786     2616    2021-07-24      41422         90.0
2        513902     3614    2021-07-24       1164          5.0
3        568405    15297    2021-07-30      15298        100.0
4        421236     6330    2021-08-01        216          4.0
...         ...      ...           ...        ...          ...
371016   166766     5693    2021-07-25        351          5.0
371017   548960     9728    2021-07-25       6523         96.0
371018   800931    11775    2021-07-30         83          1.0
371019   663351     2301    2021-07-25       9337        100.0
371020   438585     7829    2021-08-02       6804        100.0

[371021 rows x 5 columns]